# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfb6f2f9de6d8cdb29267659cde723c33339cb8aa1ec3819bdc906e8f34f3b4ebd97016f8a4d6b58b629ce04c2c726bc1e3f3c37f72b5e64eb0cf5f9d25b3ebd

test:
  secret_key_base: 2c8e8d058b8c39e46aec451b2f8dd1a52cf93e3ec752d4ecbad9b38ef64d91a6e966257b2f58e14b862f45fee7a6fe93631e82623ffbae77b9e09ca5415dc100

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
